version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: voucher-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucher_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: voucher-backend
    restart: always
    ports:
      - "4000:4000" # API
      - "5555:5555" # Prisma Studio
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/voucher_db?schema=public"
      PORT: 4000
    volumes:
      - ./backend:/app

volumes:
  pgdata:
